version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "dev"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "cron"
      cron: "1 13 * * *"
